logging:
    level:
        unlenen:
            cloud:
                openstack:
                    be: DEBUG


spring.servlet.multipart.enabled: true


openstack:
    keystone:
        url: https://os2-nfvlab.argela.com.tr:5000/v3
        system_user:
            name: argela_admin
            password: argela
            domain: default
            project: argela_admin
            
testData:
    system_user:
        name: cloud-admin
        password: argela
        domain: argela
        project: main-project
    
    identity_service:
        domain:
            name: nebi-domain10
            project:
                name: nebi-project10
            users:
                test1:
                    name: nebi_user_10
                    password: argela
                    
    compute_service:
        domain:
            name: argela
            project:
                name: main-project
        flavor:
            name: nebi-test1
            vcpus: 2
            ram: 4096
            disk: 20
        keypair:
            name: nebi-test7
            public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/I0hra2R3jo0V2CMiICefTPk8WK99n3RfqCBxESfhqxgmP8mfX1J3GY/h/4wwNy1ZwZQzCW4085oAK3Y+AdKh/blwd+2N/FExsqI/I5tHE3nMdqFP947OndLMcN8jiSaCzE1c31eKuIyng3YvOAAD9ac3glshCv+r27H35x5YXXf68RPtbhpAj914IMsYmarDWGiUadq3z9bRmZmt30I6xYvG8Z98DrWgqaIJJb0fB16mbiUggrCudqwDGfqPWxN/MwJvnnCeBt9mzH6TxkSGAbLYnRSLhdFD3jP30mGA8nLHK09GiujgkAraxms+Ouzp8ykquZrYDoKsQ/K+meiejCL2VLc5hW6lRRA07MV4vI1hz73jLfO5P9rrcbTN9Q8jA83A99uqUKjapl7TLMl9bcSkFSUWiXE6nURp+yOkK2eViBibt3C3cv/Rti5XX+j0Y0Z71P65OKzbR0XLIqX7BMzWpyssi03ziKu+kge5L82XyqoydQcP+ysDVZ8D8lM= argela@argela-HP-EliteBook-840-G2
            user:
                name: cloud-admin
        quota:
            domain: argela
            project: onurcan
        server:
            name: onurcan
            flavorRef: 6
            imageRef: 84bcc888-f31c-469b-adbb-f961d0fb04ee
            key_name: cloud
            availability_zone: nova    
            network_uuid: a54dcc04-9076-4772-a572-a91d9de24c04
            securityGroupName: onurcan

    image_service:
        domain:
            name: argela
            project:
                name: main-project
        image:
            name: ubuntuNebi
            tag: test-1

    network_service:
        security_group:
            name: onurcan
            project_id: d84321cc8bb04e30a6d04d4ca0b75c7a
            security_group_rules:
                direction: ingress
                protocol: tcp
                port_range_min: 80
                port_range_max: 80
        network:
            name: onurcan-test
            shared: false
            router_external: false
            provider_network_type: vxlan
            description: hello
            mtu: 1450
            admin_state_up: true
            port_security_enabled: false
        subnet:
            name: onurcan-test
            ip_version: 4
            cidr: 10.10.0.0/24
            allocation_pool_start: 10.10.0.2
            allocation_pool_end: 10.10.0.254
            gateaway_ip: 10.10.0.1
        floatingip:
            floating_network_id: 32de4597-026b-47a9-86c2-10c2ea88011e
            floating_ip_address: 192.168.231.107   
        router:
            name: onurcan 
            external_network_id: 32de4597-026b-47a9-86c2-10c2ea88011e

    orchestration_service:
        stack:
            name: onurcan
            templateFile: /home/argela/Downloads/template.yaml
            envFile: /home/argela/Downloads/env.yaml

    volume_service:
        volume:
            name: onurcan 
            bootable: 'true'
            size: 10
            imageRef: 84bcc888-f31c-469b-adbb-f961d0fb04ee
            new_size: 20
            instance_uuid: d8739290-edcb-4909-b980-b404c011ed53
            mountpoint: "/dev/vdc"


            